# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://HansjoergW.github.io/bfh_mt_hs2020_sec_data/"

git_url = "https://github.com/HansjoergW/bfh_mt_hs2020_sec_data/tree/master/"

def custom_doc_links(name): return None
